apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://pulsar.apache.org/charts
    chart: pulsar
    targetRevision: 3.5.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pulsar
    namespaceCreate: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true